apiVersion: v1
kind: Service
metadata:
  name: {{ template "percona-xtradb-cluster.fullname" . }}
  labels:
    app: {{ template "percona-xtradb-cluster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.publicService.enabled }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
{{- end }}
spec:
{{- if .Values.publicService.enabled }}
  type: LoadBalancer
  externalTrafficPolicy: Local
{{- if .Values.publicService.sourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.publicService.sourceRanges }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: {{ template "percona-xtradb-cluster.fullname" . }}
    release: "{{ .Release.Name }}"
